### PR TITLE
[TRRFFDA-617] Use a better password policy for all the registries

### PR DESCRIPTION
**Pull request by alintreznai**

### CODE REVIEW

**Comment by sztamas** [comment]
@alintreznai This has 2 parts. 

1. changing the validation, so it doesn't happen on the FE
2. changing the currently used password validation rules in Angelman

Can you please separate in 2 PRs, so we can apply 1. right away?

2. needs to be talked about with the client, to see if they agree with the changes.
If they do then we will also probably need TRRFFDA-636 implemented first.

**Comment by alintreznai** [comment]
Done. 
https://github.com/eresearchqut/angelman/pull/5

**Comment by sztamas** [comment]
This needs a discussion with Angelman about choosing a better password policy.
Would they be happy with our default rules in TRRF, based on the recommendation from the security experts?

**Comment by alintreznai** [comment]
Replaced by https://github.com/eresearchqut/angelman/pull/6

**Pull request closed without merging**
